  pull_request:
    branches: [ main ]

env:
  DEPLOY_VER: ${{ github.sha }}
  MONTH: "January"
  DAY_OF_THE_MONTH: "20"
  YEAR: "2022" 
  FAVORITE_DAY_OF_WEEK: ${{ secrets.FAVORITE_DAY_OF_WEEK }}

jobs:
  stage1:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
    - uses: actions/checkout@v2
    - name: Listing current dir files and folder
      run: for i in $(ls .); do echo $i; done
    - name: Print content of Log file
      run: cat log.txt
    - name: Print DEPLOY_VER variable
      run: echo "Hello from $DEPLOY_VER commit"

  stage2:
    needs: stage1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Echo day of the month 
      run: echo $DAY_OF_THE_MONTH
    - name: Print System Date
      run: date
"jekyll.yml"

